### ISSUE TITLE
Error: Error: Request failed with status code 401

### ISSUE THREAD

**Issue by doubley318** [joshcai/leetcode-sync#18]
Sorry! After I follow your tutorial, I always get this error and I don't know how to deal with it.
![image](https://user-images.githubusercontent.com/95672897/167345090-91d8eaef-06d2-4bf4-b454-8f298321576c.png)
`sync_leetcode.yml`
```
# This is a basic workflow to help you get started with Actions

name: Sync Leetcode

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # cron: 'min hour day month week (year)'
  workflow_dispatch:
  schedule:
    - cron:  '5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      - name: Sync
        uses: joshcai/leetcode-sync@v1.4
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: my-folder
# 
```
![image](https://user-images.githubusercontent.com/95672897/167345398-29826e4d-5a00-4b34-9304-146fc71c51a5.png)
And these file's contents are:
![image](https://user-images.githubusercontent.com/95672897/167345585-1081426b-de9c-47b7-bc55-eba3e88c6e5c.png)
I don't know what went wrong. 

Thank you for your help!
